import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Copy, 
  Check, 
  Sparkles, 
  FileCode, 
  Presentation, 
  Users, 
  Briefcase, 
  Eye, 
  Code,
  Printer
} from 'lucide-react';
import { playAgentChime, playSuccessFanfare } from '../utils/audio';

export default function ReportExporter({ reports = {}, projectName = 'Project' }) {
  const [activeTab, setActiveTab] = useState('readme');
  const [viewMode, setViewMode] = useState('preview'); // 'preview' | 'code'
  const [copied, setCopied] = useState(false);

  const tabs = [
    { id: 'readme', label: 'README.md', icon: FileCode },
    { id: 'meetingNotes', label: 'Meeting Notes', icon: Users },
    { id: 'statusReport', label: 'Weekly Status', icon: FileText },
    { id: 'presentationOutline', label: 'Presentation Deck', icon: Presentation },
    { id: 'clientReport', label: 'Client Briefing', icon: Briefcase }
  ];

  const currentContent = reports[activeTab] || `# ${projectName}\n\nGenerated by SprintFlow AI Agentic OS.`;

  const handleCopy = () => {
    playAgentChime(600);
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    playSuccessFanfare();
    const ext = activeTab === 'readme' ? '.md' : '.txt';
    const filename = `${projectName.toLowerCase().replace(/\s+/g, '_')}_${activeTab}${ext}`;
    const blob = new Blob([currentContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    playAgentChime(500);
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${projectName} - ${activeTab}</title>
            <style>
              body { font-family: monospace; padding: 30px; line-height: 1.6; color: #111; }
              pre { white-space: pre-wrap; }
            </style>
          </head>
          <body>
            <h2>SprintFlow AI Strategic Report: ${projectName}</h2>
            <pre>${currentContent}</pre>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center space-x-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <span>Autonomous Report Generation Center</span>
          </h3>
          <p className="text-xs text-slate-400">
            Synthesized automatically by Report Agent for instant stakeholder sharing and download.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          {/* View Mode Toggle */}
          <div className="flex items-center p-1 rounded-xl bg-slate-900 border border-slate-800 text-xs font-semibold text-slate-300">
            <button
              onClick={() => setViewMode('preview')}
              className={`flex items-center space-x-1 px-2.5 py-1 rounded-lg transition-all ${
                viewMode === 'preview' ? 'bg-slate-800 text-emerald-400 font-bold' : 'hover:text-white'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Preview</span>
            </button>
            <button
              onClick={() => setViewMode('code')}
              className={`flex items-center space-x-1 px-2.5 py-1 rounded-lg transition-all ${
                viewMode === 'code' ? 'bg-slate-800 text-emerald-400 font-bold' : 'hover:text-white'
              }`}
            >
              <Code className="w-3.5 h-3.5" />
              <span>Raw</span>
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 border border-slate-700 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-colors"
            title="Print Document"
          >
            <Printer className="w-4 h-4" />
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center space-x-1.5 px-4 py-1.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-xs font-bold text-white shadow-lg shadow-emerald-600/20 transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Artifact</span>
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center space-x-2 overflow-x-auto pb-2 border-b border-slate-800">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;

          return (
            <button
              key={tab.id}
              onClick={() => { playAgentChime(500); setActiveTab(tab.id); }}
              className={`flex items-center space-x-2 px-3.5 py-2 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                isActive
                  ? 'bg-slate-800 text-emerald-400 border border-emerald-500/40 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
              }`}
            >
              <Icon className={`w-3.5 h-3.5 ${isActive ? 'text-emerald-400' : 'text-slate-500'}`} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Document View */}
      {viewMode === 'code' ? (
        <div className="bg-slate-950 rounded-2xl border border-slate-800 p-6 font-mono text-xs text-slate-300 overflow-x-auto leading-relaxed shadow-inner max-h-[500px] overflow-y-auto">
          <pre className="whitespace-pre-wrap">{currentContent}</pre>
        </div>
      ) : (
        <div className="bg-slate-900/90 rounded-2xl border border-slate-800 p-6 text-sm text-slate-200 leading-relaxed max-h-[500px] overflow-y-auto font-sans space-y-4">
          {currentContent.split('\n\n').map((paragraph, pIdx) => {
            if (paragraph.startsWith('# ')) {
              return <h2 key={pIdx} className="text-xl font-extrabold text-white pb-2 border-b border-slate-800">{paragraph.replace('# ', '')}</h2>;
            } else if (paragraph.startsWith('## ')) {
              return <h3 key={pIdx} className="text-lg font-bold text-purple-300 pt-2">{paragraph.replace('## ', '')}</h3>;
            } else if (paragraph.startsWith('### ')) {
              return <h4 key={pIdx} className="text-base font-semibold text-emerald-400 pt-1">{paragraph.replace('### ', '')}</h4>;
            } else {
              return <p key={pIdx} className="text-slate-300 text-xs sm:text-sm font-mono leading-relaxed">{paragraph}</p>;
            }
          })}
        </div>
      )}

    </div>
  );
}
